INSERT INTO TB_AUTOR (NOME, SOBRENOME, DATA_NASCIMENTO, NACIONALIDADE) VALUES ('SAMUEL', 'PEDROSO', '1996-06-11', 'BRASILEIRO');
INSERT INTO TB_AUTOR (NOME, SOBRENOME, DATA_NASCIMENTO, NACIONALIDADE) VALUES ('CHARLES', 'DUHIGG', '1996-06-11', 'BRASILEIRO');
INSERT INTO TB_AUTOR (NOME, SOBRENOME, DATA_NASCIMENTO, NACIONALIDADE) VALUES ('CHA', 'DUHIGG', '1996-06-11', 'BRASILEIRO');